FROM quay.io/intellihr/whalebrew-pytools:3.8

LABEL io.whalebrew.name 'ptpython'
LABEL io.whalebrew.config.working_dir '/workdir'
LABEL io.whalebrew.config.volumes '["~/.ptpython:/.ptpython"]'

WORKDIR /workdir

ENTRYPOINT ["ptpython"]
